attemptDeadline: 180s
description: Scheduling Flight Data
httpTarget:
  headers:
    User-Agent: Google-Cloud-Scheduler
  httpMethod: GET
  uri: https://europe-west1-thermal-rain-423012-f5.cloudfunctions.net/flight_function
lastAttemptTime: '2024-10-14T13:24:00.203910Z'
name: projects/thermal-rain-423012-f5/locations/europe-west1/jobs/flight_schedular
retryConfig:
  maxBackoffDuration: 3600s
  maxDoublings: 5
  maxRetryDuration: 0s
  minBackoffDuration: 5s
schedule: '*/3 * * * *'
state: PAUSED
timeZone: Europe/Berlin
userUpdateTime: '2024-10-14T13:25:02Z'
